config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'welcome#index'

  resources :welcome, :only => [:index]
  resources :city, :only => [:index]
  resources :site, :only => [:index]

    namespace :api do
      namespace :v1 do
        resources :items, only: [:index, :create, :destroy, :update]
        resources :cities, only: [:index, :create, :destroy, :update]
      end
    end

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/cities_controller.rb
class Api::V1::CitiesController < Api::V1::BaseController
  def index
    respond_with City.all
  end

  def create
    respond_with :api, :v1, City.create(item_params)
  end

  def destroy
    respond_with City.destroy(params[:id])
  end

  def update
    city = City.find(params["id"])
    city.update_attributes(item_params)
    respond_with city, json: city
  end

  private

  def item_params
    params.require(:city).permit(:id, :name, :description, :data)
  end
end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < Api::V1::BaseController
  def index
    respond_with Item.all
  end

  def create
    respond_with :api, :v1, Item.create(item_params)
  end

  def destroy
    respond_with Item.destroy(params[:id])
  end

  def update
    item = Item.find(params["id"])
    item.update_attributes(item_params)
    respond_with item, json: item
  end

  private

  def item_params
    params.require(:item).permit(:id, :name, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/index.html.erb
<%= react_component 'MainOne' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Combate A Seca</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site/index.html.erb
<%= react_component 'Main' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class='preloader'><div class='loaded'>&nbsp;</div></div>

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"><a href="#home">Home</a></li>
                        <li><a href="#about">Sobre</a></li>
                        <li><a href="#portfolio">Galeria</a></li>
                        <li><a href="#notice">Notícias</a></li>
                        <li><a href="#contact">Contato</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

        <!--Home page style-->
        <header id="home" class="home">
			<div class="overlay sections">
				<div class="container">

					<div class="row">
						<div class="wrapper">
							<div class="col-md-6 col-md-offset-3">

								<div class="home-details text-center">

									<div class="logo">
										<%= image_tag("logo.png")  %>
									</div>


									<div class="scroll-down">
										<h5>Deslize para saber mais</h5>
										<a href="#about"><i class="fa fa-angle-double-down"></i></a>
									</div>

								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
        </header>

        <!-- Sections -->
        <section id="about" class="about sections">
            <div class="container">

                <!-- Example row of columns -->
                <div class="row">
                    <div class="wrapper">

                    	<div class="col-md-12 col-md-offset-2">
                    		<div class="">
								<%= video_tag "my_movie.mp4", :size => "720x640", :controls => true %>
							</div>
                    	</div>

						<div class="col-md-12">
                    		<div class="heading about-content">
								<h3>Sobre nós</h3>
								<p>Somos uma turma de alunos, estudantes do curso de Ciências da Computação, que sobre a orientação do Professor Edvan Chaves, iniciou um projeto de desenvolvimento de um software de controle de prevenção da falta de água em regições do semi-árido nordestino.</p>
								<p>Nosso intuito é fornecer um mecanismo automatizado para sinalizar os níveis de abastecimentos para comunidades onde exista instalado as cisternas fornecidas pelo governo, a fim de evitar a falta de água para as comunidades carentes do sertão.</p>
							</div>
                    	</div>


                    </div>
                </div>

				<div class="scroll-down">
					<h6>Continue a deslizar, tem mais coisa.</h6>
					<a href="#portfolio"><i class="fa fa-angle-double-down"></i></a>
				</div>

            </div> <!-- /container -->
        </section>


		<!-- Sections -->
        <section id="portfolio" class="portfolio">
			<div class="overlay sections">
				<div class="container">

					<div class="heading text-center">
						<div class="title">
							<h3>Galeria</h3>
						</div>
					</div>

					<!-- Example row of columns -->

					<div class="row">
						<div class="portfolio-wrapper">
							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("1.jpeg")  %>
									</a>
								</div>

							</div>

							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("2.jpeg")  %>
									</a>
								</div>

							</div>

							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("3.jpeg")  %>
									</a>
								</div>

							</div>

							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("4.jpeg")  %>
									</a>
								</div>

							</div>

							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("5.jpeg")  %>
									</a>
								</div>

							</div>

							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("6.jpeg")  %>
									</a>
								</div>

							</div>
							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("7.png")  %>
									</a>
								</div>

							</div>
							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("8.jpeg")  %>
									</a>
								</div>

							</div>
							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("9.jpeg")  %>
									</a>
								</div>

							</div>
							<div class="portfolio-item">

								<div class="portfolio-details">
									<a href="#" class="portfolio-img">
										<%= image_tag("10.jpeg")  %>
									</a>
								</div>

							</div>


							<div class="scroll-down">
								<h5>Alguma dúvida? Entre em contato é só deslizar mais uma vez.</h5>
								<a href="#contact"><i class="fa fa-angle-double-down"></i></a>
							</div>

						</div>
					</div>
				</div> <!-- /container -->
			</div>
        </section>


        <section id="notice" class="contact sections-notice">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="contact-details text-center">

							<div class="contact-category">

									<h4>Notícias</h4>

							</div>
						</div>
						<%= react_component 'Notice' %>
					</div>
				</div>
			</div>
		</section>


		<section id="contact" class="contact sections">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<div class="contact-details text-center">

							<div class="contact-category">
								<div class="mail">
									<h4>Email :</h4>
									<h2>matheusb982@gmail.com</h2>
								</div>
							</div>

							<div class="contact-category">
								<div class="phone">
									<h4>Telefone :</h4>
									<h5>00 11 22 33 44 55 66</h5>
								</div>
							</div>

							<div class="contact-category">
								<div class="social">
									<h4>Redes Sociais :</h4>
									<a href="#"><i class="fa fa-facebook"></i></a>
									<a href="#"><i class="fa fa-twitter"></i></a>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</section>


        <!--Footer-->
        <footer id="footer" class="footer">
            <div class="container">
            	<div class="row">
            		<div class="col-md-12">
            			<div class="copyright text-center">
            				<p>Feito com <i class="fa fa-heart"></i> por <a target="_blank" href="#"> Mb </a>2017. Todos os direitos reservados.</p>
            			</div>
            		</div>
            	</div>
            </div>
        </footer>
<!--

        <script src="assets/js/vendor/jquery-1.11.2.min.js"></script>
        <script src="assets/js/vendor/bootstrap.min.js"></script>

        <script src="assets/js/plugins.js"></script>
		<script src="assets/js/jquery.magnific-popup.js"></script>


        <script src="assets/js/main.js"></script> -->
    </body>